[package]
name = "dns-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsql = "0.3.5"
simple-dns = "0.7.0"
tokio = { version = "1.37.0", features = ["full"] }
